services:
  db:
    image: postgres:16-alpine
    container_name: swift_db_container_final
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-swift_db_final}
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -U $${POSTGRES_USER:-user} -d $${POSTGRES_DB:-swift_db_final}',
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  app:
    container_name: swift_api_container_final
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '8080:3000'
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: postgresql://${POSTGRES_USER:-user}:${POSTGRES_PASSWORD:-password}@db:5432/${POSTGRES_DB:-swift_db_final}
      CSV_FILE_PATH: ${CSV_FILE_PATH}

volumes:
  postgres-data:
